openapi: 3.0.0
info:
  title: Quizverse3D API
  version: "1.0"
paths:
  /auth/api/v1/register:
    post:
      summary: Регистрация нового пользователя
      tags:
        - Authgateway Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - username
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                username:
                  type: string
      responses:
        "201":
          description: Registered successfully
        "400":
          description: Invalid input or registration error

  /auth/api/v1/login:
    post:
      summary: Аутентификация пользователя
      tags:
        - Authgateway Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: Access token returned
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Invalid input
        "401":
          description: Unauthorized

  /auth/api/v1/validate-token:
    post:
      summary: Валидировать access-токен
      tags:
        - Authgateway Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accessToken
              properties:
                accessToken:
                  type: string
      responses:
        "200":
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
        "400":
          description: Invalid input
        "401":
          description: Unauthorized

  /auth/api/v1/update-password:
    post:
      summary: Сменить пароль
      security:
        - bearerAuth: []
      tags:
        - Authgateway Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - old_password
                - new_password
              properties:
                old_password:
                  type: string
                new_password:
                  type: string
      responses:
        "204":
          description: Пароль успешно изменён
        "400":
          description: Текущий пароль некорректный или не все обязательные параметры переданы
        "500":
          description: Внутренняя ошибка сервера

  /auth/api/v1/refresh-token:
    post:
      summary: Получить новый access-токен на основе refresh-токена
      tags:
        - Authgateway Service
      responses:
        "200":
          description: New access token issued
          content:
            text/plain:
              schema:
                type: string
        "401":
          description: Refresh token not provided or invalid

  /user/api/v1/me:
    get:
      summary: Получить информацию о пользователе текущей сессии
      tags:
        - Users Service
      description: Возвращает информацию о текущем пользователе по accessToken'у.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Информация о пользователе
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  username:
                    type: string
        "401":
          description: Unauthorized (invalid or missing token)
        "404":
          description: Пользователь не найден

  /user/api/v1/params:
    get:
      summary: Получить текущие облачные параметры клиента пользователя
      description: Возвращает текущие клиенсткие параметры пользователя (язык, громкость...).
      tags:
        - Users Service
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Параметры клиента
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_uuid:
                    type: string
                    format: uuid
                  lang_code:
                    type: string
                  sound_volume:
                    type: integer
                  is_game_sound_enabled:
                    type: boolean
        "401":
          description: Unauthorized (invalid or missing token)
        "404":
          description: Параметры пользователя не найдены
    post:
      summary: Сохранить параметры клиента в облако
      description: Можно передавать только изменённые параметры
      tags:
        - Users Service
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lang_code:
                  type: string
                sound_volume:
                  type: integer
                is_game_sound_enabled:
                  type: boolean
      responses:
        "200":
          description: Активные параметры клиента
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_uuid:
                    type: string
                    format: uuid
                  lang_code:
                    type: string
                  sound_volume:
                    type: integer
                  is_game_sound_enabled:
                    type: boolean
        "401":
          description: Unauthorized (invalid or missing token)

  /room/api/v1/room:
    put:
      summary: Создать новую комнату
      description: Создаёт на сервере новую комнату с заданными параметрами. Пароль можно не указывать. Кол-во игроков от 1 до 32 включительно.
      tags:
        - Rooms Service
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - max_players
                - is_public
              properties:
                name:
                  type: string
                  description: название комнаты
                password:
                  type: string
                  description: пароль для подключения к комнате
                max_players:
                  type: integer
                  description: максимальное кол-во игроков (1-32)
                is_public:
                  type: boolean
                  description: доступен ли в общем списке
      responses:
        "200":
          description: Параметры успешно созданной комнаты
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: id комнаты
                  owner_id:
                    type: string
                    format: uuid
                    description: id создателя
                  owner_name:
                    type: string
                    description: имя создателя
                  name:
                    type: string
                    description: название комнаты
                  max_players:
                    type: integer
                    description: максимальное кол-во игроков
                  is_public:
                    type: boolean
                    description: доступен ли в общем списке
                  created_at:
                    type: string
                    format: date-time
                    description: Время создания записи в формате ISO 8601
        "401":
          description: Unauthorized (invalid or missing token)
        "404":
          description: Invalid creation parameters
    get:
      summary: Получить информацию о комнате
      description: Не включает информацию о хеше или соли пароля
      tags:
        - Rooms Service
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: UUID комнаты
      responses:
        "200":
          description: Базовая информация о комнате
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: id комнаты
                  owner_id:
                    type: string
                    format: uuid
                    description: id создателя
                  owner_name:
                    type: string
                    description: имя создателя
                  name:
                    type: string
                    description: название комнаты
                  max_players:
                    type: integer
                    description: максимальное кол-во игроков
                  is_public:
                    type: boolean
                    description: доступен ли в общем списке
                  created_at:
                    type: string
                    format: date-time
                    description: Время создания записи в формате ISO 8601
        "401":
          description: Unauthorized (invalid or missing token)
        "404":
          description: Room not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
