apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- if .Values.env.SWAGGER_JSON }}
            - name: SWAGGER_JSON
              value: {{ .Values.env.SWAGGER_JSON | quote }}
            {{- end }}
          volumeMounts:
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap.name }}
        {{- end }}
